[theme]
primaryColor = "#0ea5e9"
backgroundColor = "#fafafa"
secondaryBackgroundColor = "#ffffff"
textColor = "#09090b"
font = "sans serif"

[server]
maxUploadSize = 200
enableXsrfProtection = true
headless = true

[browser]
gatherUsageStats = false

[client]
toolbarMode = "auto"
showErrorDetails = true